---
Name: shop-inventory--settings
After:
  - 'framework/*'
Before:
  - 'shop/*'
---
ShopConfig:
  Inventory:
    AffectStockDuring: 'placement'
    ZeroIndicatorInterval_Hours: 1
    LowIndicatorInterval_Hours: 24